// <auto-generated />
namespace BikeRentalDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedvirtualpropertys : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedvirtualpropertys));
        
        string IMigrationMetadata.Id
        {
            get { return "202004211243365_added virtual propertys"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
