// <auto-generated />
namespace BikeRentalDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class addedtotalpricevalue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addedtotalpricevalue));
        
        string IMigrationMetadata.Id
        {
            get { return "202004230717370_added totalprice value"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
